version: '3.9'
services:
  go-playground:
    container_name: go-app
    ports:
      - '8080:8080'
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
